version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: lms-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lms_db
      MYSQL_USER: lms_user
      MYSQL_PASSWORD: lms_password
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - lms-network

volumes:
  mysql-data:

networks:
  lms-network:
    driver: bridge